"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
exports.router = (0, express_1.Router)();
const Usuario_routes_1 = require("./usuarios/Usuario.routes");
const Auth_routes_1 = require("./auth/Auth.routes");
const Negocio_routes_1 = require("./negocios/Negocio.routes");
const Modulo_routes_1 = require("./modulos/Modulo.routes");
exports.router.use('/auth', Auth_routes_1.routeAuth);
exports.router.use('/usuarios', Usuario_routes_1.routeUsuario);
exports.router.use('/negocios', Negocio_routes_1.routeNegocio);
exports.router.use('/modulos', Modulo_routes_1.routeModulo);
const Condicion_routes_1 = require("./condiciones/Condicion.routes");
exports.router.use('/condiciones', Condicion_routes_1.routeCondicion);
const Version_routes_1 = require("./versiones/Version.routes");
exports.router.use('/versiones', Version_routes_1.routeVersion);
const Sucursal_routes_1 = require("./sucursales/Sucursal.routes");
exports.router.use('/sucursales', Sucursal_routes_1.routeSucursal);
const Tipo_routes_1 = require("./tipos/Tipo.routes");
exports.router.use('/tipos', Tipo_routes_1.routeTipo);
const Combustible_routes_1 = require("./combustibles/Combustible.routes");
exports.router.use('/combustibles', Combustible_routes_1.routeCombustible);
const Traccion_routes_1 = require("./tracciones/Traccion.routes");
exports.router.use('/tracciones', Traccion_routes_1.routeTraccion);
const Caja_routes_1 = require("./cajas/Caja.routes");
exports.router.use('/cajas', Caja_routes_1.routeCaja);
const Color_routes_1 = require("./colores/Color.routes");
exports.router.use('/colores', Color_routes_1.routeColor);
const Tapizado_routes_1 = require("./tapizados/Tapizado.routes");
exports.router.use('/tapizados', Tapizado_routes_1.routeTapizado);
const Direccion_routes_1 = require("./direcciones/Direccion.routes");
exports.router.use('/direcciones', Direccion_routes_1.routeDireccion);
const Valor_routes_1 = require("./valores/Valor.routes");
exports.router.use('/valores', Valor_routes_1.routeValor);
const Permuta_routes_1 = require("./permutas/Permuta.routes");
exports.router.use('/permutas', Permuta_routes_1.routePermuta);
const Marca_routes_1 = require("./marcas/Marca.routes");
exports.router.use('/marcas', Marca_routes_1.routeMarca);
const Tipomotor_routes_1 = require("./tipomotores/Tipomotor.routes");
exports.router.use('/tipomotores', Tipomotor_routes_1.routeTipomotor);
const Metododecaptacion_routes_1 = require("./metododecaptaciones/Metododecaptacion.routes");
exports.router.use('/metododecaptaciones', Metododecaptacion_routes_1.routeMetododecaptacion);
const Tipocliente_routes_1 = require("./tipoclientes/Tipocliente.routes");
exports.router.use('/tipoclientes', Tipocliente_routes_1.routeTipocliente);
const Cliente_routes_1 = require("./clientes/Cliente.routes");
exports.router.use('/clientes', Cliente_routes_1.routeCliente);
//# sourceMappingURL=index.js.map